---
title: "0.4_review_conflicts_pt1"
author: "Devi Veytia"
date: "2024-03-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set up -- run before anything else

```{r set up libraries}
## Load libraries
library(dplyr)
library(dbplyr)
library(R.utils)
library(RSQLite)
library(ggplot2)

# set up functions
sourceFn <- dir(here::here("R"))
for(i in 1:length(sourceFn)){
  source(here::here("R", sourceFn[i]))
}

```

```{r set the seed}
addTaskCallback(function(...) {set.seed(123);TRUE})
```

## Download article answers

```{r load in screening answers at title and abstract stage}

# Load answers from training screening and all screening and combine
train <- readxl::read_excel(here::here("data/derived-data/screen-train/ArticleAnswers_train_set1.xlsx"))
all <- readxl::read_excel(here::here("data/derived-data/screen-all/ArticleAnswers_conflictsResolved_2024-03-27.xlsx"))
df <- rbind(train, all)
df <- df %>%
  mutate(sysrev_id = as.numeric(`Article ID`),
         include = as.logical(Include)) %>%
  rename(title = Title) 



## This code formats User answers to wide, but don't need this because I'm using the Article answers format
# df_wide <- reshape2::dcast(formula = sysrev_id + title ~ `User Name`, value.var = 'Include',data = df)


```

# Clean data and join with metadata

```{r remove duplicates and load deduplicated data}
## Remove duplicates
#dups <- revtools::screen_duplicates(as.data.frame(df))
df_unique <- readr::read_csv(here::here("data/derived-data/screen-all/ArticleAnswers_conflictsResolved_2024-03-27_deduplicated.csv"))
df_unique$label <- NULL
df_unique$matches <- NULL

df_unique <- df_unique %>%
  left_join(df %>% dplyr::select(sysrev_id, `Exclusion criteria`), by = c("sysrev_id"))
```

```{r Write file on all the exclusions based on literature review}

reviews <- df_unique %>%
  filter(grepl("literature review", `Exclusion criteria`))
nrow(reviews) # 30 reviews -- remove these from the dataframe of conflicts

writexl::write_xlsx(reviews, here::here("data/derived-data/screen-all/ArticleAnswers_conflictsResolved_2024-03-27_literatureReviews.xlsx"))
```

```{r join with article metadata}
p4_db <- RSQLite::dbConnect(RSQLite::SQLite(),
                    here::here("data","raw-data","product4.sqlite"), 
                                create=FALSE)
screenRecs <- tbl(p4_db, "trainRecsSample") %>% collect()
dbDisconnect(p4_db)


df_unique <- fuzzyjoin::stringdist_full_join(df_unique, 
                                      screenRecs %>% 
                                        select(analysis_id, title, abstract, doi, year),
                                      by ="title", max_dist=2, ignore_case = TRUE)


# Keep title from original metadata and format/clean data frame
df_unique <- df_unique %>%
  select(sysrev_id, analysis_id, include, title.y, abstract, `Exclusion criteria`, doi, year) %>%
  rename(title = title.y)  

summary(df_unique)
nrow(df_unique)

```



```{r summarise screening results}
keyLabels <- c("Population","Intervention","Literature review","Outcome")
keyLabelCounts <- rep(NA, length(keyLabels))

for(l in 1:length(keyLabels)){
  keyLabelCounts[l] <- sum(grepl(keyLabels[l], df_unique$`Exclusion criteria`, ignore.case = TRUE))
}

sumdf <- rbind(
  data.frame(
    statistic = "Inclusion",
    label = c("Include","Exclude"),
    counts = c(sum(df_unique$include), length(df_unique$include)-sum(df_unique$include))
  ),
  data.frame(
    statistic = "Exclusion label",
    label = keyLabels,
    counts = keyLabelCounts
  )
)
sumdf$label <- factor(sumdf$label, 
                      levels = c("Include","Exclude",keyLabels))

screeningSummary_ggp <- ggplot(sumdf, aes(x=label, y=counts, fill = label))+
  geom_col()+
  geom_text(aes(label = counts), vjust = -0.2)+
  theme_bw()+
  theme(
    axis.text.x = element_text(angle = 45, vjust=1, hjust=1)
  )
screeningSummary_ggp
```

# Subset to just inclusions 

```{r automatic full text extraction}

# set scihub url to renviron 
#usethis::edit_r_environ() 
# opens .Renviron file where I add teh line of text: SCIHUB_URL = "https://sci-hub.se/"

# Subset to just the relevant articles
relevantArticles <- df_unique[df_unique$include,]
dim(relevantArticles)

# clean dois 
dois <- relevantArticles$doi
dois <- ifelse(is.na(dois), NA, gsub("https://doi.org/", "", dois))


# set directory to place downloaded pdfs
path_pdf = here::here("data/raw-data/full-texts")
if(isFALSE(dir.exists(path_pdf))){
  dir.create(path_pdf, showWarnings = FALSE, recursive = TRUE)
}

source(here::here("R/my_get_pdf.R"))

## Create a dataframe of the ids, and whether or not a pdf was found
doisFound <- data.frame(
  doi = dois,
  analysis_id = relevantArticles$analysis_id[1:length(dois)],
  title = relevantArticles$title,
  fullTextFound = logical(length(dois))
)

# download pdf if possible
for (i in 1:length(dois)) { 
  
  if (length(dois[i]) == 1) {
    if(is.na(dois[i])){
      next
    }
    
    # make filename
    id = relevantArticles$analysis_id[i]
    #auth = clean_text(substring(relevantArticles$author[i],1,10))
    tit = clean_text(substring(relevantArticles$title[i], 1, 30))
    yr = relevantArticles$year[i]
    fn = paste(id, tit, yr, sep="_") #paste(id, auth, tit, yr, sep="_")
    
 
    
    errorMessage = capture.output(my_get_pdf(doi=dois[i], path = path_pdf, filename = fn, overwrite=TRUE),
                                  type = "message")
    if(grepl("No PDF found", errorMessage)){
      doisFound$fullTextFound[i] <- FALSE
    }else{
      doisFound$fullTextFound[i] <- TRUE
    }
    
    Sys.sleep(sample(seq(0, 5, by = 0.01), 1))
  }
}


## Write results of full text retreival
write.csv(doisFound, file=here::here("data/raw-data/full-texts/results-scihub-full-text-retreival.csv"))
```


```{r write metadata to excel file}
relevantArticles %>%
  select(analysis_id, title, year, doi) %>%
  writexl::write_xlsx(path = here::here("data/derived-data/screen-all/inclusions_abstract_metadata.xlsx"))

```


```{r write search file to search in WOS to download full texts}
# Subset to just the relevant articles
relevantArticles <- df_unique[df_unique$include,]
dim(relevantArticles)

# clean dois 
dois <- relevantArticles$doi[!is.na(relevantArticles$doi)]
dois <- gsub("https://doi.org/", "", dois)
dois <- paste(dois, collapse=" OR ")
titles <- paste(relevantArticles$title[is.na(relevantArticles$doi)], collapse=" OR ")

sink(here::here("data/derived-data/screen-all/inclusions_abstract_screen_search_terms.txt"))
cat(paste0("(DO = (", dois,")) OR (TI = (", titles, "))", collapse=""))
sink()
```

```{r extract climate impact driver predictions for the relevant articles}
relevantArticles <- readxl::read_xlsx(here::here("data/derived-data/screen-all/inclusions_abstract_metadata.xlsx"))

cidPred <- read.csv(here::here("data/raw-data/coding-predictions/climate_threat_simplified_predictions.csv"))
cidPred <- cidPred[,c(1, grep("mean", colnames(cidPred)))]
colnames(cidPred) <- c("analysis_id","Temperature","Sea-level rise","Extreme weather")

relevantArticlesCid <- relevantArticles %>%
  left_join(cidPred, by="analysis_id")

relevantArticlesCid %>%
  summarise(
    nTemp = sum(0.5 <= Temperature),
    nSLR = sum(0.5 <= `Sea-level rise`),
    nExtreme = sum(0.5 <= `Extreme weather`),
  )
# # A tibble: 1 × 3
#   nTemp  nSLR nExtreme
#   <int> <int>    <int>
# 1     1    25       24

## write results
relevantArticlesCid %>%
  writexl::write_xlsx(path = here::here("data/derived-data/screen-all/inclusions_abstract_metadata_ClimateImpactDriver.xlsx"))

```


```{r count the number of article full texts retrieved}
fullTextPdf <- dir(here::here("data/raw-data/full-texts_v1"))
fullTextPdf <- as.numeric(stringr::str_extract(fullTextPdf, "^[0-9]+"))
fullTextPdf <- na.omit(fullTextPdf)
length(unique(fullTextPdf)) # 212
```



